#!/usr/bin/env python3
"""Submit all jobs from a design-point batch manifest.

This script reads a JSON manifest generated by generate_event_batches.py and
submits all jobs to the cluster (or runs them locally). It handles:
- Sequential or parallel job submission
- Automatic directory navigation
- Progress tracking
- Error handling and logging
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from datetime import datetime


def submit_job(event_folder, seed=0, dry_run=False, timeout_sec=0):
    """Submit a single event job.
    
    Args:
        event_folder: Path to the event directory
        seed: Random seed to pass to submit_job.script
        dry_run: If True, print command without executing
        
    Returns:
        (success: bool, output: str, error: str)
    """
    script_path = Path(event_folder) / "submit_job.script"
    
    if not script_path.exists():
        return False, "", f"submit_job.script not found in {event_folder}"
    
    # Build command
    command = f"bash {script_path} {seed}"
    
    if dry_run:
        print(f"[DRY RUN] {command}")
        return True, f"Would run: {command}", ""
    
    try:
        result = subprocess.run(
            command,
            shell=True,
            cwd=str(event_folder),
            capture_output=True,
            text=True,
            timeout=(timeout_sec if timeout_sec and timeout_sec > 0 else None),
        )
        
        if result.returncode == 0:
            return True, result.stdout, result.stderr
        else:
            return False, result.stdout, result.stderr
    
    except subprocess.TimeoutExpired:
        return False, "", f"Job submission timed out after {timeout_sec}s"
    except Exception as e:
        return False, "", str(e)


def main():
    parser = argparse.ArgumentParser(
        description="Submit all jobs from a design-point batch manifest",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "manifest_file",
        type=str,
        help="path to the manifest JSON file",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=0,
        help="random seed to pass to each job",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print commands without executing",
    )
    parser.add_argument(
        "--jobs",
        type=int,
        default=None,
        help="limit to first N jobs (useful for testing)",
    )
    parser.add_argument(
        "--events",
        type=int,
        default=None,
        help="limit to first N events per job",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=0,
        help="timeout in seconds for each submit_job.script call; 0 disables timeout",
    )
    parser.add_argument(
        "--log-file",
        type=str,
        default="",
        help="save submission log to this file",
    )
    args = parser.parse_args()
    
    # Load manifest
    try:
        with open(args.manifest_file, "r") as f:
            manifest = json.load(f)
    except FileNotFoundError:
        print(f"Error: Manifest file not found: {args.manifest_file}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON in manifest: {args.manifest_file}", file=sys.stderr)
        sys.exit(1)
    
    # Prepare logging
    log_lines = [
        "="*70,
        f"Job Batch Submission Log",
        f"Timestamp: {datetime.now().isoformat()}",
        f"Manifest: {args.manifest_file}",
        f"Seed: {args.seed}",
        f"Dry run: {args.dry_run}",
        f"Timeout: {args.timeout}",
        "="*70,
        ""
    ]
    
    # Get manifest info
    manifest_folder = Path(args.manifest_file).parent.absolute()
    n_total_jobs = manifest.get("n_jobs", len(manifest.get("jobs", [])))
    total_events = manifest.get("total_events", 0)
    
    jobs_to_submit = manifest.get("jobs", [])
    if args.jobs:
        jobs_to_submit = jobs_to_submit[:args.jobs]
    
    print(f"Manifest: {args.manifest_file}")
    print(f"Total jobs in manifest: {n_total_jobs}")
    print(f"Total events in manifest: {total_events}")
    print(f"Jobs to submit: {len(jobs_to_submit)}")
    if args.dry_run:
        print("[DRY RUN MODE - no jobs will be submitted]")
    if args.timeout == 0:
        print("Timeout per event: disabled")
    else:
        print(f"Timeout per event: {args.timeout}s")
    print()
    
    log_lines.append(f"Manifest: {args.manifest_file}")
    log_lines.append(f"Total jobs in manifest: {n_total_jobs}")
    log_lines.append(f"Total events in manifest: {total_events}")
    log_lines.append(f"Jobs to submit: {len(jobs_to_submit)}")
    log_lines.append(
        "Timeout per event: disabled" if args.timeout == 0
        else f"Timeout per event: {args.timeout}s"
    )
    log_lines.append("")
    
    # Submit jobs
    submitted_count = 0
    failed_count = 0
    failed_jobs = []
    
    for job_info in jobs_to_submit:
        job_id = job_info.get("job_id", "?")
        working_folder = job_info.get("working_folder", "")
        event_start = job_info.get("event_start_id", 0)
        event_end = job_info.get("event_end_id", 0)
        
        job_path = manifest_folder / working_folder
        
        if not job_path.exists():
            print(f"❌ Job {job_id}: folder not found: {job_path}")
            log_lines.append(f"❌ Job {job_id}: folder not found: {job_path}")
            failed_count += 1
            failed_jobs.append((job_id, f"folder not found: {job_path}"))
            continue
        
        print(f"Job {job_id}: {working_folder} (events {event_start}–{event_end})")
        log_lines.append(f"\nJob {job_id}: {working_folder}")
        log_lines.append(f"Events: {event_start}–{event_end}")
        
        # Submit each event
        n_events_in_job = event_end - event_start + 1
        if args.events:
            n_events_in_job = min(n_events_in_job, args.events)
        
        for local_iev in range(n_events_in_job):
            event_id = event_start + local_iev
            event_folder = job_path / f"event_{event_id}"
            
            if not event_folder.exists():
                print(f"  ⚠️  Event {event_id}: folder not found")
                log_lines.append(f"  ⚠️  Event {event_id}: folder not found")
                failed_count += 1
                failed_jobs.append((f"{job_id}:event_{event_id}", "folder not found"))
                continue
            
            success, stdout, stderr = submit_job(
                str(event_folder), args.seed, args.dry_run, args.timeout
            )
            
            if success:
                print(f"  ✓ Event {event_id} submitted")
                log_lines.append(f"  ✓ Event {event_id} submitted")
                submitted_count += 1
                if stdout:
                    log_lines.append(f"    Output: {stdout[:200]}")
            else:
                print(f"  ❌ Event {event_id} failed: {stderr[:100]}")
                log_lines.append(f"  ❌ Event {event_id} failed")
                if stderr:
                    log_lines.append(f"    Error: {stderr[:200]}")
                failed_count += 1
                failed_jobs.append((f"{job_id}:event_{event_id}", stderr[:100]))
    
    # Print summary
    print()
    print("="*70)
    print("SUBMISSION SUMMARY")
    print("="*70)
    print(f"Successfully submitted: {submitted_count}")
    print(f"Failed: {failed_count}")
    if failed_jobs:
        print("\nFailed jobs:")
        for job_name, reason in failed_jobs:
            print(f"  - {job_name}: {reason}")
    print("="*70)
    
    log_lines.extend([
        "",
        "="*70,
        "SUBMISSION SUMMARY",
        "="*70,
        f"Successfully submitted: {submitted_count}",
        f"Failed: {failed_count}",
        "="*70,
    ])
    
    # Save log if requested
    if args.log_file:
        with open(args.log_file, "w") as f:
            f.write("\n".join(log_lines))
        print(f"\nLog saved to: {args.log_file}")
    
    # Return exit code based on failures
    sys.exit(0 if failed_count == 0 else 1)


if __name__ == "__main__":
    main()
